name: ucbai_gdsc_2
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.11
  - pip

  # — Core libraries (all platforms) —
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - lightgbm
  - matplotlib
  - seaborn
  - plotly
  - shap
  - scanpy
  - anndata

  # — Excel & I/O —
  - openpyxl
  - python-wget
  - pyarrow
  - fastparquet

  # — Testing & formatting —
  - pytest
  - black
  - isort
  - flake8
  - mypy

  # — PyPI-only extras via pip —
  - pip:
    - optuna
    - category_encoders
    - imbalanced-learn
    - tabulate
    - wandb
    - pytorch-tabnet
    - torch-geometric
    - networkx
    - GEOparse
    - nbformat
    - kaleido
    - graphviz

  # — GPU & deep-learning —  
  # only install cudatoolkit + RAPIDS + PyTorch, etc. on Linux  
  - cudatoolkit=12.1    # [linux]  
  - cupy                # [linux]  
  - cudf=24.06          # [linux]  
  - cuml=24.06          # [linux]  
  - pytorch=2.3.*       # [linux]  
  - torchvision         # [linux]  
  - torchaudio          # [linux]  
  - tensorflow          # [linux]  

  # on macOS, install the Apple-optimized TensorFlow & Metal plugin  
  - tensorflow-macos    # [osx]  
  - tensorflow-metal    # [osx]  
